"use client";
// components/submit/SubmitScreen.tsx — Production fintech level

import Link from "next/link";
import { useState } from "react";

const IRS_FREE_FILE   = "https://www.irs.gov/filing/free-file-do-your-federal-taxes-for-free";
const IRS_DIRECT_FILE = "https://directfile.irs.gov";

type TaxYear = any;
function fmt(n: number) {
  return n.toLocaleString("en-US", { minimumFractionDigits: 0, maximumFractionDigits: 0 });
}

export function SubmitScreen({ taxYear }: { taxYear: TaxYear }) {
  const [copied, setCopied] = useState(false);

  const incomeItems  = taxYear.incomeItems  ?? [];
  const scenarios    = taxYear.scenarios    ?? [];
  const household    = taxYear.household;

  const best = scenarios.find((s: any) => s.type === "BALANCED")?.result
            ?? scenarios[0]?.result;

  const totalIncome      = incomeItems.reduce((s: number, i: any) => s + parseFloat(i.amount || "0"), 0);
  const totalTax         = parseFloat(best?.taxOwed           ?? "0");
  const totalWithholding = parseFloat(best?.totalWithholding  ?? "0");
  const amountDue        = parseFloat(best?.amountDue         ?? "0");
  const refund           = parseFloat(best?.refund            ?? "0");
  const agi              = parseFloat(best?.agi               ?? "0");
  const effectiveRate    = parseFloat(best?.effectiveRate     ?? "0");

  const isRefund     = refund > 0;
  const eligibleFree = agi <= 84000;
  const irsUrl       = eligibleFree ? IRS_FREE_FILE : IRS_DIRECT_FILE;
  const pdfUrl       = `/api/report/${taxYear.id}`;

  const handleCopyData = () => {
    const data = [
      `=== SolarTax — Tax Year ${taxYear.year} ===`,
      `Household: ${household?.name}`,
      `Filing Status: ${taxYear.filingStatus?.replace(/_/g, " ")}`,
      ``,
      `Total Income:      $${fmt(totalIncome)}`,
      `Adjusted Gross:    $${fmt(agi)}`,
      `Total Tax:         $${fmt(totalTax)}`,
      `Withholding:       $${fmt(totalWithholding)}`,
      `Effective Rate:    ${effectiveRate}%`,
      isRefund
        ? `REFUND:            $${fmt(refund)}`
        : `AMOUNT DUE:        $${fmt(amountDue)}`,
      ``,
      `Generated by SolarTax ☀️ — solar-tax.vercel.app`,
    ].join("\n");

    navigator.clipboard.writeText(data).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <div style={{ minHeight: "100vh", background: "var(--solar-bg)", color: "var(--solar-text)", fontFamily: "system-ui, sans-serif", paddingBottom: 100 }}>

      {/* Nav */}
      <nav style={{ borderBottom: "1px solid var(--solar-border)", background: "var(--solar-surface)", padding: "12px 24px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ fontSize: 14, fontWeight: 800, color: "var(--solar-sun)", textDecoration: "none" }}>
          ☀ Solar Tax Engine
        </Link>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          {/* Solar Verified badge */}
          <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 10, color: "var(--solar-muted)" }}>
            <span style={{ color: "var(--solar-green)" }}>✓</span> Solar Verified
            <span style={{ color: "var(--solar-border)" }}>·</span>
            <span style={{ color: "var(--solar-green)" }}>✓</span> IRS Ready
            <span style={{ color: "var(--solar-border)" }}>·</span>
            <span style={{ color: "var(--solar-green)" }}>✓</span> Secure
          </div>
          <Link href={`/tax-year/${taxYear.id}/fast-file`} style={{ fontSize: 12, color: "var(--solar-muted)", textDecoration: "none" }}>
            ← Edit return
          </Link>
        </div>
      </nav>

      <div style={{ maxWidth: 680, margin: "0 auto", padding: "40px 24px 40px" }}>

        {/* HEADER */}
        <div style={{ textAlign: "center", marginBottom: 36 }}>
          <div style={{
            display: "inline-flex", alignItems: "center", gap: 10,
            background: "rgba(16,185,129,0.08)", border: "1px solid rgba(16,185,129,0.25)",
            borderRadius: 24, padding: "8px 20px", marginBottom: 20,
          }}>
            <span style={{ fontSize: 16 }}>✅</span>
            <span style={{ fontSize: 12, fontWeight: 700, color: "var(--solar-green)", letterSpacing: .5 }}>
              SOLAR VERIFIED — Return Ready to File
            </span>
          </div>

          <h1 style={{ fontSize: 30, fontWeight: 800, letterSpacing: -1, marginBottom: 10, lineHeight: 1.1 }}>
            Your {taxYear.year} return<br />
            <span style={{ color: "var(--solar-sun)" }}>is ready to file.</span>
          </h1>
          <p style={{ fontSize: 13, color: "var(--solar-muted)" }}>
            {household?.name} · {taxYear.filingStatus?.replace(/_/g, " ")} · Tax Year {taxYear.year}
          </p>
        </div>

        {/* SUMMARY CARD */}
        <div style={{ borderRadius: 16, border: "1px solid var(--solar-border)", background: "var(--solar-surface)", overflow: "hidden", marginBottom: 16 }}>
          <div style={{ height: 3, background: "linear-gradient(90deg, var(--solar-sun), var(--solar-sun-deep))" }} />
          <div style={{ padding: "22px 24px" }}>
            <p style={{ fontSize: 10, fontWeight: 700, color: "var(--solar-sun)", letterSpacing: 1.2, marginBottom: 16, textTransform: "uppercase" }}>Tax Summary</p>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px 24px" }}>
              <SRow label="Total Income"   value={`$${fmt(totalIncome)}`} />
              <SRow label="Adjusted Gross" value={`$${fmt(agi)}`} />
              <SRow label="Total Tax"      value={`$${fmt(totalTax)}`}    color="var(--solar-red)" />
              <SRow label="Withholding"    value={`$${fmt(totalWithholding)}`} />
              <SRow label="Effective Rate" value={`${effectiveRate}%`} />
              {isRefund
                ? <SRow label="Refund"     value={`$${fmt(refund)}`}    color="var(--solar-green)" large />
                : <SRow label="Amount Due" value={`$${fmt(amountDue)}`} color="var(--solar-red)"   large />}
            </div>

            {/* Money psychology banner */}
            <div style={{
              marginTop: 16, padding: "14px 16px", borderRadius: 10,
              background: isRefund ? "rgba(16,185,129,0.08)" : "rgba(239,68,68,0.08)",
              border: `1px solid ${isRefund ? "rgba(16,185,129,0.25)" : "rgba(239,68,68,0.25)"}`,
              display: "flex", alignItems: "center", gap: 12,
            }}>
              <span style={{ fontSize: 22 }}>{isRefund ? "💰" : "📋"}</span>
              <div>
                <p style={{ fontSize: 14, fontWeight: 800, color: isRefund ? "var(--solar-green)" : "var(--solar-red)", lineHeight: 1.3 }}>
                  {isRefund
                    ? `You'll receive $${fmt(refund)} back from IRS`
                    : `You owe $${fmt(amountDue)} — file today to avoid $400 penalty`}
                </p>
                <p style={{ fontSize: 11, color: "var(--solar-muted)", marginTop: 3 }}>
                  {isRefund
                    ? "Refund arrives in 21 days when filed electronically"
                    : `Due April 15, 2026 · Pay at IRS.gov · Late filing = $${fmt(Math.round(amountDue * 0.05))}+ penalties`}
                </p>
              </div>
            </div>

            {/* Free File eligibility */}
            {eligibleFree && (
              <div style={{
                marginTop: 10, padding: "10px 14px", borderRadius: 8,
                background: "rgba(99,102,241,0.06)", border: "1px solid rgba(99,102,241,0.2)",
                display: "flex", alignItems: "center", gap: 8, fontSize: 12,
              }}>
                <span style={{ color: "#6366F1" }}>★</span>
                <span style={{ color: "#6366F1", fontWeight: 600 }}>
                  You qualify for IRS Free File
                </span>
                <span style={{ color: "var(--solar-muted)" }}>— AGI ${fmt(agi)} ≤ $84,000 limit · $0 filing cost</span>
              </div>
            )}
          </div>
        </div>

        {/* PREFILL COPY */}
        <div style={{
          borderRadius: 12, border: "1px solid var(--solar-border)",
          background: "var(--solar-surface)", padding: "16px 20px", marginBottom: 16,
          display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16,
        }}>
          <div>
            <p style={{ fontSize: 13, fontWeight: 700, color: "var(--solar-text)", marginBottom: 3 }}>📋 Copy tax data to clipboard</p>
            <p style={{ fontSize: 11, color: "var(--solar-muted)" }}>
              Paste directly into IRS Free File — income, withholding, and all figures
            </p>
          </div>
          <button
            onClick={handleCopyData}
            style={{
              padding: "9px 18px", borderRadius: 8, border: "1px solid var(--solar-border)",
              background: copied ? "rgba(16,185,129,0.1)" : "var(--solar-bg)",
              color: copied ? "var(--solar-green)" : "var(--solar-text)",
              fontSize: 12, fontWeight: 700, cursor: "pointer",
              whiteSpace: "nowrap", transition: "all .2s",
              borderColor: copied ? "rgba(16,185,129,0.3)" : "var(--solar-border)",
            }}
          >
            {copied ? "✓ Copied!" : "Copy data"}
          </button>
        </div>

        {/* READINESS CHECKLIST */}
        <div style={{ borderRadius: 12, border: "1px solid var(--solar-border)", background: "var(--solar-surface)", padding: "18px 22px", marginBottom: 16 }}>
          <p style={{ fontSize: 10, fontWeight: 700, color: "var(--solar-muted)", letterSpacing: 1, marginBottom: 12, textTransform: "uppercase" }}>Filing Readiness</p>
          {[
            "Income data validated",
            "Expense deductions applied",
            `Tax calculated with ${taxYear.year} IRS brackets`,
            "PDF export generated",
            incomeItems.length > 0 && `${incomeItems.length} income source${incomeItems.length > 1 ? "s" : ""} included`,
            eligibleFree && "Qualifies for IRS Free File ($0 cost)",
          ].filter(Boolean).map((item: any) => (
            <div key={item} style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 7 }}>
              <span style={{ color: "var(--solar-green)", fontWeight: 700, fontSize: 13 }}>✓</span>
              <span style={{ fontSize: 13 }}>{item}</span>
            </div>
          ))}
        </div>

        {/* HOW TO FILE */}
        <div style={{ borderRadius: 12, border: "1px solid var(--solar-border)", background: "var(--solar-surface)", padding: "18px 22px", marginBottom: 24 }}>
          <p style={{ fontSize: 10, fontWeight: 700, color: "var(--solar-muted)", letterSpacing: 1, marginBottom: 14, textTransform: "uppercase" }}>How to File</p>
          <Step n="1" title="Download your Solar Tax PDF" desc="Your complete return with all figures." />
          <Step n="2" title={eligibleFree ? "Go to IRS Free File — $0" : "Go to IRS Direct File"} desc={eligibleFree ? `Your AGI $${fmt(agi)} qualifies. Free filing, no cost.` : "Direct e-file for simple returns."} />
          <Step n="3" title="Enter or paste your figures" desc="Use 'Copy data' above to paste directly. Takes 5 minutes." />
          <Step n="4" title="Submit electronically" desc={isRefund ? `Refund of $${fmt(refund)} arrives in 21 days.` : `Pay $${fmt(amountDue)} to avoid penalties.`} />
        </div>

        {/* ACTION BUTTONS */}
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          <a href={irsUrl} target="_blank" rel="noopener noreferrer" style={{
            display: "flex", alignItems: "center", justifyContent: "center", gap: 10,
            padding: "16px 28px", borderRadius: 12, textDecoration: "none",
            background: "linear-gradient(135deg, var(--solar-sun), var(--solar-sun-deep))",
            color: "#000", fontSize: 15, fontWeight: 800,
            boxShadow: "0 6px 24px rgba(232,85,0,0.22)",
          }}>
            ☀ File with IRS {eligibleFree ? "Free File" : "Direct File"} →
            <span style={{ fontSize: 10, opacity: .6 }}>irs.gov</span>
          </a>

          <div style={{ display: "flex", gap: 10 }}>
            <a href={pdfUrl} download style={{
              flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
              padding: "12px", borderRadius: 10, textDecoration: "none",
              border: "1px solid var(--solar-border)", background: "var(--solar-surface)",
              color: "var(--solar-text)", fontSize: 13, fontWeight: 700,
            }}>
              📄 Download PDF
            </a>
            <a href={eligibleFree ? IRS_DIRECT_FILE : IRS_FREE_FILE} target="_blank" rel="noopener noreferrer" style={{
              flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8,
              padding: "12px", borderRadius: 10, textDecoration: "none",
              border: "1px solid rgba(59,130,246,0.3)", background: "rgba(59,130,246,0.06)",
              color: "#3B82F6", fontSize: 13, fontWeight: 700,
            }}>
              ⚡ {eligibleFree ? "IRS Direct File" : "IRS Free File"}
            </a>
          </div>
        </div>

        {/* DISCLAIMER */}
        <div style={{ marginTop: 24, padding: "14px 18px", borderRadius: 10, background: "var(--solar-surface)", border: "1px solid var(--solar-border)", fontSize: 11, color: "var(--solar-muted)", lineHeight: 1.7 }}>
          <strong style={{ color: "var(--solar-text)" }}>Important:</strong>{" "}
          SolarTax is a tax optimization tool, not a filing service. Not affiliated with the IRS.
          Filing is completed on the official IRS website (irs.gov). Consult a licensed CPA before filing.
          Penalty for late filing may apply after April 15, 2026.
        </div>
      </div>

      {/* ── STICKY BOTTOM BAR ── */}
      <div style={{
        position: "fixed", bottom: 0, left: 0, right: 0, zIndex: 50,
        background: "var(--solar-surface)",
        borderTop: "1px solid var(--solar-border)",
        boxShadow: "0 -4px 24px rgba(0,0,0,0.08)",
        backdropFilter: "blur(12px)",
      }}>
        <div style={{
          maxWidth: 680, margin: "0 auto",
          padding: "12px 24px",
          display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16,
        }}>
          <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
            <span style={{ fontSize: 13, fontWeight: 700, color: "var(--solar-text)" }}>
              {isRefund
                ? `💰 $${fmt(refund)} refund — file now to receive it`
                : `📋 $${fmt(amountDue)} due — file today to avoid penalty`}
            </span>
            <span style={{ fontSize: 11, color: "var(--solar-muted)" }}>
              {eligibleFree ? "✓ Qualifies for $0 IRS Free File" : "IRS Direct File available"}
            </span>
          </div>
          <a
            href={irsUrl}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: "inline-flex", alignItems: "center", gap: 8,
              padding: "11px 24px", borderRadius: 10, textDecoration: "none",
              background: "linear-gradient(135deg, var(--solar-sun), var(--solar-sun-deep))",
              color: "#000", fontSize: 13, fontWeight: 800,
              whiteSpace: "nowrap",
              boxShadow: "0 4px 16px rgba(232,85,0,0.20)",
            }}
          >
            ☀ File Now →
          </a>
        </div>
      </div>
    </div>
  );
}

function SRow({ label, value, color, large }: { label: string; value: string; color?: string; large?: boolean }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "7px 0", borderBottom: "1px solid var(--solar-border)" }}>
      <span style={{ fontSize: 12, color: "var(--solar-muted)" }}>{label}</span>
      <span style={{ fontSize: large ? 18 : 13, fontWeight: large ? 800 : 600, color: color ?? "var(--solar-text)", fontFamily: large ? "system-ui" : "inherit" }}>
        {value}
      </span>
    </div>
  );
}

function Step({ n, title, desc }: { n: string; title: string; desc: string }) {
  return (
    <div style={{ display: "flex", gap: 14, marginBottom: 12, alignItems: "flex-start" }}>
      <div style={{
        width: 24, height: 24, borderRadius: "50%", flexShrink: 0,
        background: "rgba(232,85,0,0.10)", border: "1px solid rgba(232,85,0,0.25)",
        display: "flex", alignItems: "center", justifyContent: "center",
        fontSize: 10, fontWeight: 800, color: "var(--solar-sun)",
      }}>{n}</div>
      <div>
        <p style={{ fontSize: 13, fontWeight: 700, marginBottom: 2 }}>{title}</p>
        <p style={{ fontSize: 11, color: "var(--solar-muted)", lineHeight: 1.6 }}>{desc}</p>
      </div>
    </div>
  );
}
