// lib/reporting/irs1040-map.ts
// Maps internal ScenarioResult + TaxYear data → IRS 1040 line items
// Deterministic — no AI, no estimation.

import type { IRS1040Report, ReportIncomeItem, ReportExpenseItem, ReportDependent } from "./types";
import { filingStatusLabel } from "./format";

function cents(val: string | undefined): number {
  return parseFloat(val ?? "0") || 0;
}

function fmt(n: number): string {
  return Math.round(n).toString();
}

export function buildIRS1040Report(input: {
  taxYear:        any;
  bestScenario:   any;
  scenarioResult: any;
}): IRS1040Report {
  const { taxYear, bestScenario, scenarioResult: r } = input;

  const grossIncome      = cents(r.grossIncome);
  const allowedExpenses  = cents(r.allowedExpenses);
  const netProfit        = cents(r.netProfit);
  const seTax            = cents(r.seTax);
  const deductibleSEhalf = cents(r.deductibleSEhalf);
  const agi              = cents(r.agi);
  const standardDed      = cents(r.standardDeduction);
  const taxableIncome    = cents(r.taxableIncome);
  const childTaxCredit   = cents(r.childTaxCredit);
  const totalCredits     = cents(r.totalCredits);
  const taxOwed          = cents(r.taxOwed);
  const totalWithholding = cents(r.totalWithholding);
  const refund           = cents(r.refundAmount);
  const amountDue        = cents(r.amountDue);

  // W-2 income
  const w2Income = (taxYear.incomeItems ?? [])
    .filter((i: any) => i.type === "W2")
    .reduce((sum: number, i: any) => sum + cents(i.amount), 0);

  // SE income (1099 etc)
  const seIncome = (taxYear.incomeItems ?? [])
    .filter((i: any) => i.type !== "W2")
    .reduce((sum: number, i: any) => sum + cents(i.amount), 0);

  // Line mapping
  // Line 1a = W-2 wages
  const line1a = w2Income > 0 ? fmt(w2Income) : undefined;
  // Line 1z = total wages (same as 1a here)
  // Line 8 = additional income (SE net profit goes to Schedule 1)
  const line8 = seIncome > 0 ? fmt(netProfit > 0 ? netProfit : seIncome) : undefined;
  // Line 9 = total income
  const line9 = fmt(grossIncome);
  // Line 10 = adjustments (deductible SE half)
  const line10 = deductibleSEhalf > 0 ? fmt(deductibleSEhalf) : undefined;
  // Line 11 = AGI
  const line11 = fmt(agi);
  // Line 12 = standard deduction
  const line12 = fmt(standardDed);
  // Line 15 = taxable income
  const line15 = fmt(Math.max(0, taxableIncome));
  // Line 16 = income tax (total - SE tax)
  const incomeTax = Math.max(0, taxOwed - seTax + totalCredits);
  const line16 = fmt(incomeTax);
  // Line 18 = income tax before credits
  const line18 = fmt(incomeTax + totalCredits);
  // Line 19 = child tax credit
  const line19 = totalCredits > 0 ? fmt(totalCredits) : undefined;
  // Line 22 = tax after credits
  const line22 = fmt(Math.max(0, incomeTax));
  // Line 23 = SE tax
  const line23 = seTax > 0 ? fmt(seTax) : undefined;
  // Line 24 = total tax
  const line24 = fmt(taxOwed);
  // Line 25d = total withholding
  const line25d = totalWithholding > 0 ? fmt(totalWithholding) : undefined;
  // Line 33 = total payments
  const line33 = fmt(totalWithholding);
  // Line 35a = refund
  const line35a = refund > 0 ? fmt(refund) : undefined;
  // Line 37 = amount owed
  const line37 = amountDue > 0 ? fmt(amountDue) : undefined;

  // Source breakdowns
  const incomeItems: ReportIncomeItem[] = (taxYear.incomeItems ?? []).map((i: any) => ({
    type:        i.type,
    source:      i.source,
    amount:      i.amount,
    withholding: i.withholding ?? "0",
  }));

  const expenseItems: ReportExpenseItem[] = (taxYear.expenseItems ?? []).map((e: any) => ({
    category:    e.category,
    description: e.description,
    amount:      e.amount,
    businessPct: e.businessPct,
    allowed:     fmt(cents(e.amount) * e.businessPct / 100),
  }));

  const dependents: ReportDependent[] = (taxYear.dependents ?? []).map((d: any) => ({
    firstName:    d.firstName,
    lastName:     d.lastName,
    relationship: d.relationship,
    months:       d.months,
  }));

  const household = taxYear.household;
  const taxpayerName = household?.name ?? "Taxpayer";

  return {
    taxYear:       taxYear.year,
    filingStatus:  filingStatusLabel(taxYear.filingStatus),
    taxpayerName,

    line1a,
    line8,
    line9,
    line10,
    line11,
    line12,
    line13:  undefined,
    line14:  fmt(standardDed),
    line15,
    line16,
    line18,
    line19,
    line22,
    line23,
    line24,
    line25d,
    line33,
    line35a,
    line37,

    generatedAt:  new Date().toISOString(),
    scenarioUsed: bestScenario?.name ?? "Balanced",
    notes: [
      "Generated by Solar Tax Engine — for planning purposes only.",
      "Consult a licensed tax professional before filing.",
    ],

    incomeItems,
    expenseItems,
    dependents,
  };
}
